version: '3.8'
services:

  web:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "9777:8001"
  db:
    container_name: db
    image: postgres:12
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local